######################################################################
# This is the template used to generate auto-publication workflows for
# the different documents in the repository. Check generate script for
# details. Edit this file and run the script again to update the
# workflows.
######################################################################

name: Publish {{shortname}} on /TR

on:
  pull_request:
    paths:
      - "{{shortname}}/**"
  push:
    branches: [main]
    paths:
      - "{{shortname}}/**"
  workflow_dispatch:

jobs:
  publish-TR-{{shortname}}:
    name: Publish {{shortname}}
    if: github.repository == 'w3c/csswg-drafts'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: w3c/spec-prod@v2
        with:
          TOOLCHAIN: bikeshed
          SOURCE: {{shortname}}/Overview.bs
          DESTINATION: {{shortname}}/index.html
          BUILD_FAIL_ON: warning
          VALIDATE_MARKUP: false
          W3C_ECHIDNA_TOKEN: ${{ secrets.{{tokenName}} }}
          W3C_WG_DECISION_URL: https://www.w3.org/2025/08/21-css-minutes.html#fc30
          W3C_BUILD_OVERRIDE: |
            status: {{publicationStatus}}
