<pre class='metadata'>
Title: CSS Linked Parameters Module Level 1
Shortname: css-link-params
Level: 1
Status: FPWD
Date: 2026-07-14
Prepare for TR: Yes
Group: CSSWG
Work Status: refining
ED: https://drafts.csswg.org/css-link-params/
TR: https://www.w3.org/TR/css-link-params-1/
Editor: Tab Atkins-Bittner, Google, http://xanthir.com/contact/, w3cid 42199
Editor: Daniel Holbert, Mozilla, w3cid 41734
Editor: Jonathan Watt, Mozilla, w3cid 34802
Abstract: This spec introduces a way to pass CSS values into linked resources, such as SVG images, so that they can be used as CSS [=custom environment variables=] in the destination resource. This allows easy reuse of "templated" SVG images, which can be adapted to a site's theme color, etc. easily, without having to modify the source SVG.
Ignored Terms: css value definition syntax
</pre>

<pre class="link-defaults">
spec:selectors-4; type:selector; text::hover
spec:html; type:element
	text: iframe
	text: a
spec:fill-stroke-3; type:property; text:fill
spec:css-env-1; type:function; text:env()
spec:scroll-to-text-fragment; type:dfn; 
	text:fragment directive
	text:text directive
</pre>

Introduction {#intro}
=====================

SVG is stylable with CSS,
and when used inline in HTML,
this capability can be very useful.
For example, an SVG icon can take on a different color based on whether the user is hovering it or not,
just by applying a '':hover'' rule to it that changes the 'fill' property.

When the SVG is referenced in a way that doesn't allow selectors or CSS inheritance from the outer page to apply to it
(such as embedding it via <{img}> or <{iframe}> in HTML),
though, this functionality is lost.
The only way to change the display of such "external" SVG images
is to produce several of them,
and change which image you're referencing.
This incurs delay on the page as a new resource is downloaded,
and disallows dynamic effects like CSS Transitions.

<dfn export lt="CSS link parameter" local-lt="link parameter">CSS link parameters</dfn>
are a way to set CSS <a>custom environment variables</a> on an "external" resource,
either by a CSS property
or thru a special fragment scheme on the URL.
This gives a limited, but powerful, subset of the customizability that "inline" SVG images have
to "external" SVG images,
or to other linked resources that use CSS to style themselves.

A [=link parameter=] is a pair of a <<dashed-ident>> name,
and an arbitrary (possibly empty) <<declaration-value>> value.

<div class=example>
	For example, an SVG image can be written to use [=link parameters=],
	allowing it to have its colors changed on the fly,
	like:

	<xmp highlight=html>
		<svg>
			<path fill="env(--color, black)" d="..." />
		</svg>
	</xmp>

	By default, it will fill its shape with black,
	as that's the fallback color specified.
	But [=link parameters=] can customize the color
	in several ways:

	<xmp highlight=html>
		<img src="image.svg#:~:param(--color,green)">
	</xmp>

	<pre highlight=css>
		img {
			link-parameters: param(--color, green);
		}
	</pre>

	<pre highlight=css>
		.foo {
			background-image: url("image.svg", param(--color, green));
		}
	</pre>
</div>

Setting a Link Parameter {#setting}
===================================

An external resource can be accompanied by a list of [=link parameters=],
each entry composed of a <<dashed-ident>> as a key,
and a (possibly empty) <<declaration-value>> as the value.

There are three ways to specify a [=link parameter=]:

* via the 'link-parameters' property,
	which applies to the resource itself
	(if the element represents an external resource),
	and to all external resources used in CSS properties on the element
* via a [=fragment directive=] directly in the URL of an external resource.
* via a ''param()'' argument in the ''url()'' syntax

If specified in multiple of these ways,
all of the [=link parameters=] are appended into a single list
for the external resource,
in the order:

1. the 'link-parameters' property on the element, if relevant
2. the [=link parameter directives=] of the URL
3. the ''param()'' <<url-modifier>>s in ''url()''

If multiple [=link parameters=] exist with the same name,
the last one in the list is used.

How to access [=link parameters=] in the linked resource
is defined in the next section,
[[#using]].


The ''param()'' Function {#param}
------------------------

All three methods of setting [=link parameters=]
share the same syntax for <em>defining</em> a parameter,
using the <dfn>param()</dfn> function:

<pre class=prod>
	param() = param( <<param-name>> , <<declaration-value>>? )
	<dfn><<param-name>></dfn> = color | accent-color | <<dashed-ident>>
</pre>

Depending on the <<param-name>>,
the [=link parameter=] has slightly different effects on the linked resource,
and a different default value:

<dl dfn-type=value dfn-for="param(), <param-name>">
	: <dfn>color</dfn>
	:: Sets the [=initial value=] of the 'color' property on the linked resource,
		and defaults to the value of the 'color' property on the linking element.

	: <dfn>accent-color</dfn>
	:: Sets the [=initial value=] of the 'accent-color' property on the linked resource,
		and defaults to the value of the 'accent-color' property on the linking element.

	: <dfn><<dashed-ident>></dfn>
	:: Sets a [=custom environment variable=] of the given name on the linked resource,
		and defaults to the value of the [=custom property=] of the same name on the linking element.
</dl>

The second argument, if provided, gives the value of the [=linked parameter=].
If not specified, the [=linked parameter=]'s value is the default value.

A completely empty second argument is valid,
and is indicated by specifying the comma separating it from the first argument.

<div class=example>
	That is, ''param(--foo)'' indicates that the [=link parameter=] is using the default value,
	drawing from the '--foo' [=custom property=] on the element.

	On the other hand, ''param(--foo,)'' explicitly gives the [=link parameter=] an empty value.

	This is similar to ''var(--foo)'' having no fallback,
	but ''var(--foo,)'' having an empty fallback.
</div>


For An Entire Element: the 'link-parameters' property {#link-param-prop}
-----------------------------------------------------

<pre class=propdef>
Name: link-parameters
Value: none | <<param()>>#
Initial: none
Inherited: no
Applies to: all elements and pseudo-elements
Computed value: as specified
Animation type: discrete
</pre>

The 'link-parameters' property is one way to set [=link parameters=]
on the element itself
(if it is an element representing an external resource,
such as an HTML <{img}> or <{iframe}>),
and on all external CSS resources specified on the element
(such as background images, etc).
Its values are:

<dl dfn-type=value dfn-for=none>
	: <dfn>none</dfn>
	:: No [=link parameters=] are specified.

	: <dfn><<param()>>#</dfn>
	:: A list of one or more [=link parameters=].
</dl>


For A Single URL: the ''url()'' Function {#setting-url}
----------------------------------------

While 'link-parameters' sets [=link parameters=] for <em>every</em> URL on an element,
sometimes you want to set parameters for only one resource,
or use the same resource multiple times on an element with different parameters.
For this, you can use ''param()'' directly in the ''url()'' function,
as a <<url-modifier>>.

<div class="example">
	For example,
	if the site is using a ''--primary-color'' custom property to theme its elements with,
	and wanted an SVG background using ''env(--color)'' to reflect it,
	it could write:

	<pre highlight=css>
		.foo {
			background-image: url(
				"http://example.com/image.svg"
				param(--color, var(--primary-color))
			);
		}
	</pre>
</div>


Outside Of CSS: in the URL itself {#url-frag}
---------------------------------

[=Link parameters=] can be used outside of CSS,
by embedding them directly into the URL as a [=fragment directive=].

Note: [=Text directives=] are another example of [=fragment directives=],
letting you link to specific text somewhere in a document.

The <dfn export>link parameter directive</dfn> is a [=fragment directive=]
with the following syntax:

```
:~:param(...)
```

Where the <code>...</code> represents any sequence of URL codepoints and/or <l spec=url>[=percent-encoded bytes=]</l>.

After URL-decoding, the [=link parameter directive=] is then [=CSS/parsed=] as a <<param()>>.
If it fails to parse, the directive is ignored.
Otherwise, it's added to the embedded document's list of link parameters,
with a name given by the <<dashed-ident>> and a value given by the <<declaration-value>>?.

<div class="example">
	For example, to set the ''env(--text-color)'' [=custom environment variable=]
	of an SVG image to ''blue'',
	one can reference the image with a url like
	“<code>http://example.com/image.svg#:~:param(--text-color,blue)</code>”.
</div>

Multiple [=link parameters=] can be passed to an image
by appending multiple [=link parameter directives=] to the URL.
When combined, either with each other or with other "fragment identifiers",
each value is separated with an <code>&</code> character,
as in a URL's query parameters.

<div class="example">
	For example, if the image from the previous example also used ''env(--bg-color)'',
	it could be referenced with a url like
	“<code>http://example.com/image.svg#:~:param(--text-color,blue)&amp;param(--bg-color,white)</code>”
	to set both ''env(--text-color)'' and ''env(--bg-color)''.
</div>

Note: Spaces, and some other characters that might be valid in CSS syntax,
are not technically valid in URLs.
In some contexts,
you might need to escape those characters to form a valid URL.
In most cases, though,
such as HTML's <{a}> element or CSS's ''url()'' function,
spaces are accepted and do not need to be escaped.

Using Link Parameters {#using}
=====================

When an external resource link has one or more [=link parameters=] specified,
if the linked resource understands CSS
(such as an SVG or HTML document),
then those [=link parameters=]
establish global [=custom environment variables=] for the resource
with their name and value,
accessible with the ''env()'' function in stylesheets.

<div class="example">
	For example, if an SVG image wanted to expose a ''--color'' parameter,
	it could use it like:

	<xmp highlight=html>
		<svg>
			<g style="fill: env(--color);">
				<path d="..." />
			</g>
		</svg>
	</xmp>
</div>

<div class="note">
	It's usually a good idea to make your SVG image usable even if no parameters are given,
	by providing "default values" for each of the custom properties.
	There are several ways to do this.

	1. On each ''env()'' function, provide a fallback value, like ''fill: env(--color, blue)''.
	2. If the ''env()'' is going to be used a lot,
		such that providing a fallback for each individual ''env()'' is troublesome,
		store the [=custom environment variable=] in a [=custom property=] on the root element
		with the default specified,
		like:

		<pre class="lang-css">
			:root {
				--color: env(--color, blue);
			}
		</pre>

		In this example, if ''--color'' is provided via a [=linked parameter=],
		''var(--color)'' will contain its value.
		If not, it will contain the default ''blue'' value.
		In either case, ''var(--color)'' can be used in the stylesheet unconditionally,
		secure in the knowledge that it will always have a value.
</div>


<h2 class="no-num no-ref" id=priv>
Privacy Considerations</h2>

This specification introduces no new privacy considerations.

<h2 class="no-num no-ref" id=sec>
Security Considerations</h2>

This specification introduces a new way to pass information to a linked resource,
potentially from a hostile source.

While no explicit handshake is established for this channel,
the use of ''env()'' to use the information
minimizes the chance that the linked resource
can be <em>surprised</em> by the information.
The only way for the page to be vulnerable
is to somehow be using an <em>unknown</em> ''env()'' in their styles,
which will just result in invalid properties by default,
and be visible in the developer's Dev Tools.

Any hostile information can also only affect
individual CSS properties that the resource explicitly opts itself into.
