[Documentation=
 "<p>The {@name} {@type} represents an <code>@charset</code> rule.</p>"
]
interface CSSCharsetRule : CSSRule {

  [Documentation=
   "<p>The {@name} {@type} must return the encoding information specified by the <code>@charset</code> rule.</p>"
  ]
  attribute DOMString encoding;

};
