[Documentation=
 "<p>The {@name} {@type} represents a <code>@font-face</code> rule.</p>"
]
interface CSSFontFaceRule : CSSRule {

  [Documentation=
   "<p>The {@name} {@type} must return a <code>CSSStyleDeclaration</code> block that contains the property\
    declarations specified within the <code>@font-face</code> rule.</p>"
  ]
  readonly attribute CSSStyleDeclaration style;

};
