[Documentation=
 "<p>The {@name} {@type} represents an <code>@import</code> rule.</p>"
]
interface CSSImportRule : CSSRule {

  [Documentation=
   "<p>The {@name} {@type} must return the <span>URL</span> specified by the <code>@import</code> rule.</p>\
    <p class='note'>To get the resolved <span>URL</span> use the <code title='dom-StyleSheet-href'>href</code>\
    attribute of the associated <span>style sheet</span>.</p>"
  ]
  readonly attribute DOMString href;

  [PutForwards=mediaText,
   Documentation=
   "<p>The {@name} {@type} must return the value of the <code title='dom-StyleSheet-media'>media</code>\
    attribute of the associated <span>style sheet</span>.</p>"
  ]
  readonly attribute MediaList media;

  [Documentation=
   "<p>The {@name} {@type} must return the associated <span>style sheet</span>.</p>\
    <p class='note'>If loading of the style sheet fails its <code title='dom-CSSStyleSheet-cssRules'>cssRules</code>\
    list is simply empty, i.e., an <code>@import</code> rule always has an associated <span>style sheet</span>.</p>"
  ]
  readonly attribute CSSStyleSheet styleSheet;

};
