[Documentation=
 "<p>The {@name} {@type} represents a <code>@media</code> rule.</p>"
]
interface CSSMediaRule : CSSRule {

  [PutForwards=mediaText,
   Documentation=
   "<p>The {@name} {@type} must return a <code>MediaList</code> object for the list of media queries specified\
    with the <code>@media</code> rule.</p>"
  ]
  readonly attribute MediaList media;

  [Documentation=
   "<p>The {@name} {@type} must return a <code>CSSRuleList</code> object for the list of CSS rules specified\
    with the <code>@media</code> rule.</p>"
  ]
  readonly attribute CSSRuleList cssRules;

  [Documentation=
   "<p>The {@name} {@type} must <span>insert a CSS rule</span> <var>rule</var> into the CSS rule list\
    returned by <code title='dom-CSSMediaRule-cssRules'>cssRules</code> at <var>index</var>.</p>"
  ]
  unsigned long insertRule(DOMString rule, in unsigned long index);

  [Documentation=
   "<p>The {@name} {@type} must <span>remove a CSS rule</span> from the CSS rule list returned by\
    <code title='dom-CSSMediaRule-cssRules'>cssRules</code> at <var>index</var>.</p>"
  ]
  void deleteRule(unsigned long index);

};
