[Documentation=
 "<p>The {@name} {@type} represents a <code>@namespace</code> rule.</p>"
]
interface CSSNamespaceRule : CSSRule {

  [Documentation=
   "<p>The {@name} {@type} must return the namespace of the <code>@namespace</code> rule.</p>"
  ]
  readonly attribute DOMString namespaceURI;

  [Documentation=
   "<p>The {@name} {@type} must return the prefix of the <code>@namespace</code> rule or the\
    empty string if there is no prefix.</p>"
  ]
  readonly attribute DOMString? prefix;
};
