[Documentation=
 "<p>The {@name} {@type} represents a <code>@page</code> rule.</p>\
  <p class='note'>Need to define the rules for\
  <dfn id='parse-a-css-page-selector'>parse a CSS page selector</dfn> and\
  <dfn id='serialize-a-css-page-selector'>serialize a CSS page selector</dfn>.</p>"
]
interface CSSPageRule : CSSRule {

  [Documentation=
   "<p>The {@name} {@type}, on getting, must return the result of <span title='serialize a CSS page selector'>serializing</span>\
    the associated <span>CSS page selector</span>.</p>\
    <p>On setting the {@name} {@type} these steps must be run:</p>\
    <ol>\
    <li><p>Run the <span>parse a CSS page selector</span> algorithm on the given value.</p></li>\
    <li><p>If the algorithm returns a non-null value replace the associated <span>CSS page selector</span> with the returned value.</p></li>\
    <li><p>Otherwise, if the algorithm returns a <code>null</code> value, do nothing.</p></li>\
    </ol>"
  ]
  attribute DOMString selectorText;

  [Documentation=
   "<p>The {@name} {@type} must return a <code>CSSStyleDeclaration</code> for the <code>@page</code> rule.</p>"
  ]
  readonly attribute CSSStyleDeclaration style;

};
