//
// All members defined since DOM-2 Style. The only differences are:
//
//   1. removal of UNKNOWN_RULE = 0 constant
//   2. removal of CHARSET_RULE = 1 constant
//   3. addition of NAMESPACE_RULE = 10 constant
//   4. removal of commented raises(DOMException) on setting cssText
//

[Documentation=
 "<p>The {@name} {@type} represents an abstract, base CSS style rule. Each\
  distinct CSS style rule type is represented by a distinct {@type} that\
  inherits from this {@type}.</p>"
]
interface CSSRule {
  const unsigned short STYLE_RULE = 1;
  const unsigned short IMPORT_RULE = 3;
  const unsigned short MEDIA_RULE = 4;
  const unsigned short FONT_FACE_RULE = 5;
  const unsigned short PAGE_RULE = 6;
  const unsigned short NAMESPACE_RULE = 10;

  [Documentation=
   "<p>The {@name} {@type} must return the <span>CSS rule</span> type, as follows:</p>\
    <dl class='switch'>\
     <dt><code>STYLE_RULE</code></dt>\
     <dd>The object is a <code>CSSStyleRule</code>.</dd>\
     <dt><code>IMPORT_RULE</code></dt>\
     <dd>The object is a <code>CSSImportRule</code>.</dd>\
     <dt><code>MEDIA_RULE</code></dt>\
     <dd>The object is a <code>CSSMediaRule</code>.</dd>\
     <dt><code>FONT_FACE_RULE</code></dt>\
     <dd>The object is a <code>CSSFontFaceRule</code>.</dd>\
     <dt><code>PAGE_RULE</code></dt>\
     <dd>The object is a <code>CSSPageRule</code>.</dd>\
     <dt><code>NAMESPACE_RULE</code></dt>\
     <dd>The object is a <code>CSSNamespaceRule</code>.</dd>\
    </dl>\
    <p class='note'>Constants with values 0 and 2 have been obsoleted by this\
    specification. They might be re-allocated in the future.\
    <p class='note'>Constants for new and proprietary features are coordinated\
    on the <a href='http://wiki.csswg.org/spec/cssom-constants'>CSSOM Constants</a> wiki page.</p>"
  ]
  readonly attribute unsigned short type;

  [Documentation=
   "<p>The {@name} {@type} must return a <span title='serialize a CSS rule'>serialization</span> of the\
    <span>CSS rule</span>.</p>\
    <p>On setting the {@name} {@type} these steps must be run:</p>\
    <ol>\
     <li><p><span title='Parse a CSS rule'>Parse</span> the value.</p></li>\
     <li><p>If parsing failed terminate this algorithm.</p></li>\
     <li><p>If the <code title='dom-CSSRule-type'>type</code> of the new\
     object does not match the <code title='dom-CSSRule-type'>type</code> of\
     the current object\
     <span data-anolis-spec=dom title=concept-throw>throw</span> an\
     '<code data-anolis-spec=dom>InvalidModificationError</code>' exception.</li>\
     <li><p>Replace the current object with the new object.</p></li>\
    </ol>"
  ]
  attribute DOMString cssText;

  [Documentation=
   "<p>The {@name} {@type} must return the nearest enclosing rule of the current rule or null, if\
    there is no enclosing rule.</p>\
    <p class='note'>For example, <code>@media</code> can enclose a rule.</p>"
  ]
  readonly attribute CSSRule parentRule;

  [Documentation=
   "<p>The {@name} {@type} must return the <code>CSSStyleSheet</code> object that contains the the\
    current rule.</p>"
  ]
  readonly attribute CSSStyleSheet parentStyleSheet;

};
