//
// All members defined since DOM-2 Style. The only differences are:
//
//   1. removal of raises(DOMException) on {insert,delete}Rule operations.
//

[Documentation=
 "<p>The {@name} {@type} represents a CSS <span>style sheet</span> rule.</p>"
]
interface CSSStyleSheet : StyleSheet {

  [Documentation=
   "<p>The {@name} {@type} must return the <span>style sheet owner CSS rule</span>.</p>"
  ]
  readonly attribute CSSRule ownerRule;

  [Documentation=
   "<p>The {@name} {@type} must return a <code>CSSRuleList</code> object representing the <span>style\
    sheet CSS rules</span>.</p>\
    <p class='note'>CSS rules that were dropped during parsing can not be\
    found using APIs described by this specification.</p>"
  ]
  readonly attribute CSSRuleList cssRules;

  [Documentation=
   "<p>The {@name} {@type} must <span>insert a CSS rule</span> <var>rule</var> the in CSS rule\
    list returned by <code title='dom-CSSStyleSheet-cssRules'>cssRules</code> at\
    <var>index</var>.</p>"
  ]
  unsigned long insertRule(DOMString rule, unsigned long index);

  [Documentation=
   "<p>The {@name} {@type} must <span>remove a CSS rule</span> from the CSS rule list returned by\
    <code title='dom-CSSStyleSheet-cssRules'>cssRules</code> at <var>index</var>.</p>"
  ]
  void deleteRule(unsigned long index);

};
