//
// All members defined since DOM-2 Style. The only differences are:
//
//   1. removal of commented raises(DOMException) on setting cssText
//   2. removal of raises(DOMException) on {set,remove}Property
//   3. removal of getPropertyCSSValue() method
//
interface CSSStyleDeclaration {
           attribute DOMString cssText;

  readonly attribute unsigned long length;
  DOMString item(unsigned long index);

  DOMString getPropertyValue(DOMString property);
  DOMString getPropertyPriority(DOMString property);
  void setProperty(DOMString property, DOMString value, optional DOMString priority);
  DOMString removeProperty(DOMString property);

  readonly attribute CSSRule parentRule;
};
