//
// All members defined since DOM-2 Style. The only differences are:
//
//   1. removal of commented raises(DOMException) on setting selectorText
//

[Documentation=
 "<p>The {@name} {@type} represents a rule set.</p>"
]
interface CSSStyleRule : CSSRule {

  [Documentation=
   "<p>The {@name} {@type}, on getting, must return the result of <span title='serialize a group of selectors'>serializing</span> the associated\
    <span>group of selectors</span>.</p>\
    <p>On setting the {@name} {@type} these steps must be run:</p>\
    <ol>\
      <li><p>Run the <span>parse a group of selectors</span> algorithm on the given value.</p></li>\
      <li><p>If the algorithm returns a non-null value replace the associated <span>group of selectors</span> with the returned value.</p></li>\
      <li><p>Otherwise, if the algorithm returns a <code>null</code> value, do nothing.</p></li>\
    </ol>"
  ]
  attribute DOMString selectorText;

  [Documentation=
   "<p>The {@name} {@type} must return a <code>CSSStyleDeclaration</code> object for the rule set.</p>"
  ]
  readonly attribute CSSStyleDeclaration style;
};
