[NoInterfaceObject,
 Documentation=
 "The {@name} {@type} is implemented by <code>Element</code> objects in order to provide access to inline style properties."
]
interface ElementCSSInlineStyle {

  [Documentation=
   "The {@name} {@type} must return a mutable <code>CSSStyleDeclaration</code> object\
    that represents the inline style properties of the associated <code>Element</code> instance."
  ]
  readonly attribute CSSStyleDeclaration style;

};
