partial interface Element {

  [Documentation=
   "<!--ATRISK--><p>The {@name} {@type} must run the following steps:\
    <ol>\
      <li><p>If <var>pseudoElt</var> is as an <span data-anolis-spec=dom>ASCII case-insensitive</span> match for either '<code>:before</code>' or\
      '<code>::before</code>' return the <code>PseudoElement</code> representing the '::before' pseudo-element of the <span data-anolis-spec=dom>context\
      object</span>.</p></li>\
      <li><p>If <var>pseudoElt</var> is as an <span data-anolis-spec=dom>ASCII case-insensitive</span> match for either '<code>:after</code>' or\
      '<code>::after</code>' return the <code>PseudoElement</code> representing the '::after' pseudo-element of the <span data-anolis-spec=dom>context\
      object</span>.</p></li>\
      <li><p>Return null.</p></li>\
    </ol>\
    <p>When invoked with an argument that returns a <code>PseudoElement</code> object representing a particular pseudo-element, the same object must be\
    returned as returned by an earlier call that represent the same pseudo-element.</p>"
  ]
  PseudoElement? pseudo (DOMString pseudoElt);
};

Element implements GetStyleUtils;
