[NoInterfaceObject,
 Documentation=
 "<p>The {@name} {@type} provides access to inline style properties of an element.</p>"
]
interface ElementCSSInlineStyle {

  [Documentation=
   "<p>The {@name} {@type} must return a <span>CSS declaration block</span> with the\
    <span>CSS declaration block declarations</span> being set to the declarations\
    specified in the element's <code title>style</code> content attribute. If the\
    <code title>style</code> content attribute is absent, the object represents an empty\
    declaration. Mutating the <code>CSSStyleDeclaration</code> object must set the\
    <code title>style</code> content attribute on the element to the\
    <span title='serialize a CSS declaration block'>serialization</span> of the\
    <code>CSSStyleDeclaration</code>'s <span>CSS declaration block declarations</span>.\
    The same object must be returned each time. The object is be live; if the\
    <code title>style</code> content attribute is set, changed or removed, the <span>CSS\
    declaration block declarations</span> must be updated as appropriate.</p>"
  ,
  PutForwards=cssText] readonly attribute CSSStyleDeclaration style;

};
