[NoInterfaceObject, Documentation=
"<p>The <dfn>associated document</dfn> of an object <var>obj</var> is <var>obj</var>'s <span data-anolis-spec=dom title=concept-node-document>node\
 document</span> if <var>obj</var> is an <code>Element</code> object, or <var>obj</var>'s associated <code>Element</code> object's\
 <span data-anolis-spec=dom title=concept-node-document>node document</span> if <var>obj</var> is a <code>PseudoElement</code> object.</p>"
]
interface GetStyleUtils {

  [Documentation=
   "<!--ATRISK--><p>The {@name} {@type} must return a <span>CSS declaration block</span> with the\
    <span>CSS declaration block readonly flag</span> set and the\
    <span>CSS declaration block declarations</span> set to all properties\
    the user agent supports with as value the <span>specified value</span>\
    computed for the <span data-anolis-spec=dom>context object</span> using the style rules associated\
    with the <span data-anolis-spec=dom>context object</span>'s <span>associated document</span>.</p>"
  ]
  readonly attribute CSSStyleDeclaration specifiedStyle;

  [Documentation=
   "<!--ATRISK--><p>The {@name} {@type} must return a <span>CSS declaration block</span> with the <span>CSS declaration block readonly flag</span> set and the\
    <span>CSS declaration block declarations</span> set to all properties the user agent supports with as value the <span>computed value</span> computed for\
    the <span data-anolis-spec=dom>context object</span> using the user agent-level style rules and user-level style rules associated with the\
    <span data-anolis-spec=dom>context object</span>'s <span>associated document</span>, ignoring transitions, animations, author-level style\
    rules, author-level presentational hints and override-level style rules.</p>"
  ]
  readonly attribute CSSStyleDeclaration defaultStyle;

  [Documentation=
   "<!--ATRISK--><p>The {@name} {@type} must return a <span>CSS declaration block</span> with the\
    <span>CSS declaration block readonly flag</span> set and the\
    <span>CSS declaration block declarations</span> set to all properties\
    the user agent supports with as value the <span>computed value</span>\
    computed for the <span data-anolis-spec=dom>context object</span> using the style rules associated\
    with the <span data-anolis-spec=dom>context object</span>'s <span>associated document</span>.</p>"
  ]
  readonly attribute CSSStyleDeclaration computedStyle;

  [Documentation=
   "<!--ATRISK--><p>The {@name} {@type} must return a <span>CSS declaration block</span> with the\
    <span>CSS declaration block readonly flag</span> set and the\
    <span>CSS declaration block declarations</span> set to all properties\
    the user agent supports with as value the <span>used value</span>\
    computed for the <span data-anolis-spec=dom>context object</span> using the style rules associated\
    with the <span data-anolis-spec=dom>context object</span>'s <span>associated document</span>.</p>"
  ]
  readonly attribute CSSStyleDeclaration usedStyle;

};
