[NoInterfaceObject,
 Documentation=
 "<p>The <dfn id='associated-style-sheet'>associated style sheet</dfn> of a node is the <span>style sheet</span> in the list of\
  <span>document style sheets</span> of which the <span>style sheet owner node</span> implements the {@name} {@type}.</p>"
]
interface LinkStyle {

  [Documentation=
   "<p>The {@name} {@type} must return the <span>associated style sheet</span> for the node or <code>null</code>\
    if there is no <span>associated style sheet</span>.</p>"
  ]
  readonly attribute StyleSheet? sheet;

};

