//
// All members defined since DOM-2 Style. The only differences are:
//
//   1. addition of stringifier qualifier on mediaText
//   2. addition of getter qualifier on item
//   3. removal of raises(DOMException) from {append,delete}Medium
//

[Documentation=
 "<p>An object that implements the {@link} {@type} has an associated <dfn>collection of media queries</dfn>.</p>",
 [ Documentation=
   "<p>To <dfn id='create-a-medialist-object'>create a <code>MediaList</code> object</dfn> from a string <var>text</var>, run these steps:</p>\
   <ol>\
    <li><p>Create a new {@name} object.</p></li>\
    <li><p>Set its <span title='dom-MediaList-mediaText'>mediaText</span> attribute to <var>text</var>.</p></li>\
    <li><p>Return the newly created <code>{@name}</code> object.</p></li>\
   </ol>"
 ]
 Constructor(DOMString text)
]
interface MediaList {

  [Documentation=
   "<p>The {@name} {@type} must return a <span title='serialize a media query list'>serialization</span>\
   of the <span>collection of media queries</span>.</p>\
   <p>Setting the {@name} {@type} must run these steps:\
   <ol>\
    <li><p>Empty the <span>collection of media queries</span>.</p></li>\
    <li><p>If the given value is the empty string terminate these steps.</p></li>\
    <li><p>Append all the media queries as a result of <span title='parse a media query list'>parsing</span> the given\
    value to the <span>collection of media queries</span>.</p></li>\
   </ol>"
  ]
  stringifier attribute DOMString mediaText;

  [Documentation=
   "<p>The {@name} {@type} must return the number of media queries in the <span>collection of media queries</span>.</p>"
  ]
  readonly attribute unsigned long length;

  [Documentation=
   "<p>The {@name} method must return the media query in the <span>collection of media queries</span> given by\
   <var>index</var>, or null, if <var>index</var> is greater than or equal to the number of media queries in the\
   <span>collection of media queries</span>.</p>"
  ]
  getter DOMString item(unsigned long index);

  [Documentation=
   "<p>The {@name} method must run these steps:</p>\
   <ol>\
    <li><p>Let <var>m</var> be the result of <span title='parse a media query'>parsing</span> the given value.</p></li>\
    <li><p>If <var>m</var> is null terminate these steps.</p></li>\
    <li><p>If <span title='compare media queries'>comparing</span> <var>m</var> with any of the media queries in the\
    <span>collection of media queries</span> returns true terminate these steps.</p></li>\
    <li><p>Append <var>m</var> to the <span>collection of media queries</span>.</p></li>\
   </ol>"
  ]
  void appendMedium(DOMString medium);

  [Documentation=
   "<p>The {@name} method must run these steps:</p>\
   <ol>\
    <li><p>Let <var>m</var> be the result of <span title='parse a media query'>parsing</span> the given value.</p></li>\
    <li><p>If <var>m</var> is null terminate these steps.</p></li>\
    <li><p>Remove any media query from the <span>collection of media queries</span> for which\
    <span title='compare media queries'>comparing</span> the media query with <var>m</var> returns true.</p></li>\
   </ol>"
  ]
  void deleteMedium(DOMString medium);
};
