[Documentation=
 "<!--ATRISK--><p>The {@name} {@type} is used for representing CSS pseudo-elements. A {@name} object is associated with an <code>Element</code> object.</p>"
]

interface PseudoElement {
};

PseudoElement implements GetStyleUtils;
