//
// All members defined since DOM-2 Style. Only difference
// is addition of [PutForwards=mediaText], which is presently
// not defined in CSSOM draft.
//

[Documentation=
 "<p>The {@name} {@type} represents an abstract, base style sheet.</p>"
]
interface StyleSheet {

  [Documentation=
   "<p>The {@name} {@type} must return the <span>style sheet type</span>.</p>"
  ]
  readonly attribute DOMString type;

  [Documentation=
   "<p>The {@name} {@type} must return the <span>style sheet location</span> or null if none.</p>\
    <p class='issue'>What should the default value be if not known or specified upon creation? an empty string or null?</p>"
  ]
  readonly attribute DOMString? href;

  [Documentation=
   "<p>The {@name} {@type} must return the <span>style sheet owner node</span>.</p>\
    <p class='issue'>Should {@name} be nullable?</p>"
  ]
  readonly attribute Node ownerNode;

  [Documentation=
   "<p>The {@name} {@type} must return the <span>style sheet parent</span> or null if there is none.</p>"
  ]
  readonly attribute StyleSheet? parentStyleSheet;

  [Documentation=
   "<p>The {@name} {@type} must return the <span>style sheet title</span> or null if none.</p>\
    <p class='issue'>What should the default value be if not known or specified upon creation? an empty string or null?</p>"
  ]
  readonly attribute DOMString? title;

  [Documentation=
   "<p>The {@name} {@type} must return the <span>style sheet media</span>.</p>\
    <p class='issue'>Should {@name} be nullable?</p>\
    <p class='issue'>Need to define a setter that implements the semantics of setting this attribute to a string representing a MediaList.</p>"
  ]
  readonly attribute MediaList media;

  [Documentation=
   "<p>The {@name} {@type} must return true if the <span>style sheet disabled flag</span>\
    is set, or false otherwise.</p>\
    <p>Setting the {@name} {@type} must set the <span>style sheet disabled flag</span>\
    if the new value is true, or unset the <span>style sheet disabled flag</span> otherwise.</p>"
  ]
  attribute boolean disabled;
};
