# Use this command with local bikeshed:
# bikeshed spec Overview.bs Overview.html

# spec-generator can be used, but sending only Overview.bs will lose img width/height generation
# curl https://www.w3.org/publications/spec-generator/ -F type=bikeshed-spec -F file=@Overview.bs > Overview.html
