<pre class='metadata'>
Title: CSS Fonts Module Level 4
Shortname: css-fonts
Level: 4
Status: ED
Work Status: Exploring
Group: CSSWG
ED: https://dev.w3.org/csswg/css-fonts-4/
Editor: John Daggett, Mozilla, jdaggett@mozilla.com
Abstract: This specification defines modifications to the existing <a href="https://dev.w3.org/csswg/css-fonts-3/">CSS Fonts 3</a> specification along with additional experimental features.
Ignored Terms: font-palette, <named-palette-color>
</pre>

<pre class="link-defaults">
spec:css-color-4; type:property; text:color
</pre>

<h2 id="introduction">Introduction</h2>

<p></p>

<h2 id="font-palette-control">Controlling font palette colors</h2>

<div>
	Resolved at 2015 Sydney to add font-palette control.
	<a href="https://lists.w3.org/Archives/Public/www-style/2015Feb/0211.html">Original proposal</a>.

	Details: multicolor fonts now exist.
	They expose several "palette indexes" that can be given different colors.
	They might also expose predefined palettes.
	We want to be able to tell the browser to use a predefined palette,
	or to provide our own colors for a palette.

	Final proposal is:

	1. Add a 'font-palette' property.  For now the grammar is just:

		<pre class=prod><<integer>> | light | dark | <<named-palette-color>#</pre>

		with <<integer>> selecting the nth palette in the font,
		and ''light'' and ''dark'' selecting the first palette designated "light" or "dark"
		(this is metadata that's already part of the format).
		If there's any font fallback, the fallback fonts don't use a palette.
	2. Add ''@palette-entries'' to ''@font-feature-values'',
		with the name of each declaration defining a name for a particular palette color,
		and the value being an integer for the index of that palette color.
		<<named-palette-color>> is <code><<ident>> <<color>></code>.
		Any palette colors not given an explicit value default to value of 'color'
		(so by default it just renders solidly with 'color' value, as normal).
		If a palette color name occurs more than once, the last one wins
		(so you can declare a palette in a variable, and override bits as desired).
</div>

<h2 id="expanded-font-weight-scale">Expanding the scale of <code>font-weight</code></h2>

<p>Expand the range of weights possible within the <code>font-weight</code>
property and <code>font-weight</code> descriptor to include integer values within
the range [1..999].</p>

<h2 id="system-generic-font">The <code>system</code> generic font</h2>

<p>Define a new <code>system</code> generic font that maps to the default user
interface font used on a given system.</p>

<h2 id="min-max-font-size">Minimum and maximum <code>font-size</code></h2>

<p>Define new properties to control the minimum and maximum font-size,
<code>min-font-size</code> and <code>max-font-size</code>.</p>

<h2 class="no-num" id="acknowledgments">Acknowledgments</h2>
