
[Documentation=
 "<p>A <dfn>caret position</dfn> gives the position of a text insertion point indicator. It always has an associated\
  <dfn>caret node</dfn>, <dfn>caret offset</dfn>, and <dfn>caret range</dfn>. It is represented by a {@name} {@type}.</p>"
]
interface CaretPosition {

  [Documentation=
   "<p>The {@name} {@type}  must return the <span>caret node</span>.</p>"
  ]
  readonly attribute Node offsetNode;

  [Documentation=
   "<p>The {@name} {@type}  must return the <span>caret offset</span>.</p>"
  ]
  readonly attribute unsigned long offset;

};
