
[Documentation=
 "<p>Objects implementing the {@name} {@type} represent a rectangular box. The type of box is specified by the method that returns a {@name} {@type}.</p>"
]
interface ClientRect {

  [Documentation=
   "<p>The {@name} {@type} must return the y-coordinate, relative to the <span>viewport</span> origin, of the top of the rectangle box.</p>"
  ]
  readonly attribute double top;

  [Documentation=
   "<p>The {@name} {@type} must return the x-coordinate, relative to the <span>viewport</span> origin, of the right of the rectangle box.</p>"
  ]
  readonly attribute double right;

  [Documentation=
   "<p>The {@name} {@type} must return the y-coordinate, relative to the <span>viewport</span> origin, of the bottom of the rectangle box.</p>"
  ]
  readonly attribute double bottom;

  [Documentation=
   "<p>The {@name} {@type} must return the x-coordinate, relative to the <span>viewport</span> origin, of the left of the rectangle box.</p>"
  ]
  readonly attribute double left;

  [Documentation=
   "<p>The {@name} {@type} must return the width of the rectangle box.</p>\
    <p class='note'>This is identical to <code title='widl-ClientRect-right'>right</code> minus <code title='widl-ClientRect-left'>left</code>.</p>"
  ]
  readonly attribute double width;

  [Documentation=
   "<p>The {@name} {@type} must return the height of the rectangle box.</p>\
    <p class='note'>This is identical to <code title='widl-ClientRect-bottom'>bottom</code> minus <code title='widl-ClientRect-top'>top</code>.</p>"
  ]
  readonly attribute double height;

};
