
[Documentation=
 "<p>The {@name} {@type} consists of an ordered list of <code>ClientRect</code> objects.</p>"
]
interface ClientRectList {

  [Documentation=
   "<p>The {@name} {@type} must return the total number of <code>ClientRect</code> objects associated with the object.</p>"
  ]
  readonly attribute unsigned long length;

  [Documentation=
   "<p>The {@name} {@type}, when invoked, must throw an <code data-anolis-spec=dom>IndexSizeError</code> exception when <var title>index</var> is\
    greater than the number of <code>ClientRect</code> objects associated with the object. Otherwise, the <code>ClientRect</code> object at\
    <var title>index</var> must be returned.</p>"
  ]
  getter ClientRect item(unsigned long index);

};
