
partial interface HTMLElement {

  [Documentation=
   "<p>The {@name} {@type} must return the result of running these steps:</p>\
    <ol>\
     <li>\
      <p>If any of the following holds true return null and terminate this\
      algorithm:</p>\
      <ul>\
       <li>The element does not have an associated <span>CSS layout box</span>.</li>\
       <li>The element is the root element.</li>\
       <li>The element is <span>the HTML <code>body</code> element</span>.</li>\
       <li>The element's computed value of the '<code>position</code>' property is <code>fixed</code>.</li>\
      </ul>\
     </li>\
     <li>\
      <p>Return the nearest ancestor element of the element for which at least\
      one of the following is true and terminate this algorithm if such an\
      ancestor is found:</p>\
      <ul>\
       <li>The computed value of the '<code>position</code>' property is not <code>static</code>.</li>\
       <li>It is <span>the HTML <code>body</code> element</span>.</li>\
       <li>The computed value of the '<code>position</code>' property of\
       the element is <code>static</code> and the ancestor is one of the\
       following <span data-anolis-spec=html title='HTML elements'>HTML elements</span>:\
       <code>td</code>, <code>th</code>, or <code>table</code>.</li>\
      </ul>\
     </li>\
     <li><p>Return null.</p></li>\
    </ol>"
  ]
  readonly attribute Element offsetParent;

  [Documentation=
   "<p>The {@name} {@type} must return the result of running these steps:</p>\
    <ol>\
     <li><p>If the element is <span>the HTML <code>body</code> element</span>\
     or does not have any associated <span>CSS layout box</span> return zero and terminate\
     this algorithm.</p></li>\
     <li><p>If the <code title=dom-HTMLElement-offsetParent>offsetParent</code> of the element is null return the\
     y-coordinate of the top <span>border edge</span> of the first\
     <span>CSS layout box</span> associated with the element, relative to the\
     <span>initial containing block</span> origin, and terminate this\
     algorithm.</p></li>\
     <li>\
      <p>Return the result of subtracting the y-coordinate of the top\
      <span>padding edge</span> of the first <span>CSS layout box</span> associated with\
      the <code title=dom-HTMLElement-offsetParent>offsetParent</code> of the element from the y-coordinate of\
      the top <span>border edge</span> of the first <span>CSS layout box</span> associated\
      with the element, relative to the <span>initial containing block</span>\
      origin.</p>\
      <p class='note'>An inline element that consists of multiple line boxes\
      will only have its first <span>CSS layout box</span> considered.</p>\
     </li>\
    </ol>"
  ]
  readonly attribute long offsetTop;

  [Documentation=
   "<p>The {@name{} {@type} must return the result of running these steps:</p>\
    <ol>\
     <li><p>If the element is <span>the HTML <code>body</code>\
     element</span> or does not have any associated <span>CSS layout box</span> return zero\
     and terminate this algorithm.</p></li>\
     <li><p>If the <code title=dom-HTMLElement-offsetParent>offsetParent</code> of the element is null return the\
     x-coordinate of the left <span>border edge</span> of the first\
     <span>CSS layout box</span> associated with the element, relative to the\
     <span>initial containing block</span> origin, and terminate this\
     algorithm.</p></li>\
     <li>\
      <p>Return the result of subtracting the x-coordinate of the left\
      <span>padding edge</span> of the first <span>CSS layout box</span> associated with\
      the <code title=dom-HTMLElement-offsetParent>offsetParent</code> of the element from the x-coordinate of\
      the left <span>border edge</span> of the first <span>CSS layout box</span> associated\
      with the element, relative to the <span>initial containing block</span>\
      origin.</p>\
     </li>\
    </ol>"
  ]
  readonly attribute long offsetLeft;

  [Documentation=
   "<p>The {@name} {@type} must return the result of running these steps:</p>\
    <ol>\
     <li><p>If the element does not have any associated <span>CSS layout box</span> return zero and terminate this algorithm.</p></li>\
     <li><p>Return the <span>border edge</span> width of the first <span>CSS layout box</span> associated with the element.</p></li>\
    </ol>"
  ]
  readonly attribute long offsetWidth;

  [Documentation=
   "<p>The {@name} {@type} must return the result of running these steps:</p>\
    <ol>\
     <li><p>If the element does not have any associated <span>CSS layout box</span> return zero and terminate this algorithm.</p></li>\
     <li><p>Return the <span>border edge</span> height of the first <span>CSS layout box</span> associated with the element.</p></li>\
    </ol>"
  ]
  readonly attribute long offsetHeight;

};
