
partial interface MouseEvent {


  [Documentation=
   "<p>The {@name} {@type} must return the x-coordinate of\
    the position where the event occurred relative to the origin of the\
    screen.</p>"
  ]
  readonly attribute long screenX;

  [Documentation=
   "<p>The {@name} {@type} must return the y-coordinate of\
    the position where the event occurred relative to the origin of the\
    screen.</p>"
  ]
  readonly attribute long screenY;

  [Documentation=
   "<p>The {@name} {@type} must return the horizontal coordinate of\
    the position where the event occurred relative to\
    the origin of the <span>initial containing block</span>.</p>"
  ]
  readonly attribute long pageX;

  [Documentation=
   "<p>The {@name} {@type} must return the y-coordinate of the\
    position where the event occurred relative to the origin of the\
    <span>initial containing block</span>.</p>"
  ]
  readonly attribute long pageY;

  [Documentation=
   "<p>The {@name} {@type} must return the x-coordinate of\
    the position where the event occurred relative to the origin of the\
    <span>viewport</span>.</p>"
  ]
  readonly attribute long clientX;

  [Documentation=
   "<p>The {@name} {@type} must return the y-coordinate of\
    the position where the event occurred relative to the origin of the\
    <span>viewport</span>.</p>"
  ]
  readonly attribute long clientY;

  [Documentation=
   "<p>The {@name} {@type} must return the value of <code title=widl-MouseEvent-clientX>clientX</code>.</p>"
  ]
  readonly attribute long x;

  [Documentation=
   "<p>The {@name} {@type} must return the value of <code title=widl-MouseEvent-clientY>clientY</code>.</p>"
  ]
  readonly attribute long y;

  [Documentation=
   "<p>The {@name} {@type} must return the x-coordinate of\
    the position where the event occurred relative to the origin of the\
    <span>padding edge</span> of the target node.</p>"
  ]
  readonly attribute long offsetX;

  [Documentation=
   "<p>The {@name} {@type} must return the y-coordinate of\
    the position where the event occurred relative to the origin of the\
    <span>padding edge</span> of the target node.</p>"
  ]
  readonly attribute long offsetY;

};
