
partial interface MouseEvent {


  [Documentation=
   "<p>The {@name} {@type} must return the x-coordinate of\
    the position where the event occurred relative to the origin of the\
    screen.</p>"
  ]
  readonly attribute double screenX;

  [Documentation=
   "<p>The {@name} {@type} must return the y-coordinate of\
    the position where the event occurred relative to the origin of the\
    screen.</p>"
  ]
  readonly attribute double screenY;

  [Documentation=
   "<p>The {@name} {@type} must return the horizontal coordinate of\
    the position where the event occurred relative to\
    the origin of the <span>initial containing block</span>.</p>"
  ]
  readonly attribute double pageX;

  [Documentation=
   "<p>The {@name} {@type} must return the y-coordinate of the\
    position where the event occurred relative to the origin of the\
    <span>initial containing block</span>.</p>"
  ]
  readonly attribute double pageY;

  [Documentation=
   "<p>The {@name} {@type} must return the x-coordinate of\
    the position where the event occurred relative to the origin of the\
    <span>viewport</span>.</p>"
  ]
  readonly attribute double clientX;

  [Documentation=
   "<p>The {@name} {@type} must return the y-coordinate of\
    the position where the event occurred relative to the origin of the\
    <span>viewport</span>.</p>"
  ]
  readonly attribute double clientY;

  [Documentation=
   "<p>The {@name} {@type} must return the value of <code title=widl-MouseEvent-clientX>clientX</code>.</p>"
  ]
  readonly attribute double x;

  [Documentation=
   "<p>The {@name} {@type} must return the value of <code title=widl-MouseEvent-clientY>clientY</code>.</p>"
  ]
  readonly attribute double y;

  [Documentation=
   "<p>The {@name} {@type} must return the x-coordinate of\
    the position where the event occurred relative to the origin of the\
    <span>padding edge</span> of the target node.</p>"
  ]
  readonly attribute double offsetX;

  [Documentation=
   "<p>The {@name} {@type} must return the y-coordinate of\
    the position where the event occurred relative to the origin of the\
    <span>padding edge</span> of the target node.</p>"
  ]
  readonly attribute double offsetY;

};
