
partial interface Range {

  [Documentation=
   "<p>The {@name} {@type}, when invoked, must return an empty\
    <code>ClientRectList</code> object if the range is not in the document and\
    otherwise a <code>ClientRectList</code> object containing a list of\
    <code>ClientRect</code> objects in content order that matches the\
    following constraints:</p>\
    <ul>\
     <li>For each element selected by the range, whose parent is not selected\
     by the range, include the border boxes returned by invoking\
     <code title=widl-Element-getClientRects>getClientRects()</code> on the\
     element.</li>\
     <li>For each <code>Text</code> node selected or partially selected by the\
     range (including when the boundary-points are identical), include a\
     <code>ClientRect</code> object (for the part that is selected, not the\
     whole line box). The bounds of these <code>ClientRect</code> objects are\
     computed using font metrics; thus, for horizontal writing, the vertical\
     dimension of each box is determined by the font ascent and descent, and\
     the horizontal dimension by the text advance width.</li>\
    </ul>"
  ]
  ClientRectList getClientRects();

  [Documentation=
   "<p>The {@name} {@type}, when invoked, must return the result of the following algorithm:</p>\
    <ol>\
     <li><p>Let <var>list</var> be the result of invoking\
     <code title=widl-Range-getClientRects>getClientRects()</code> on the\
     same range this method was invoked on.</p></li>\
     <li><p>If <var>list</var> is empty return a\
     <code>ClientRect</code> object whose\
     <code title=widl-ClientRect-top>top</code>,\
     <code title=widl-ClientRect-right>right</code>,\
     <code title=widl-ClientRect-bottom>bottom</code> and\
     <code title=widl-ClientRect-left>left</code> members are zero.</p></li>\
     <li><p>Otherwise, return a <code>ClientRect</code> object describing the\
     smallest rectangle that includes the first rectangle in <var>list</var>\
     and all of the remaining rectangles of which the height or width is not\
     zero.</p></li>\
    </ol>"
  ]
  ClientRect getBoundingClientRect();

};
