
[Documentation=
 "<p>As its name suggests, the {@name} {@type} represents information about the screen of the output device.</p>"
]
interface Screen {

  [Documentation=
   "<p>The {@name} {@type} must return the available width of the rendering surface of the output device.</p>"
  ]
  readonly attribute unsigned long availWidth;

  [Documentation=
   "<p>The {@name} {@type} must return the available height of the rendering surface of the output device.</p>"
  ]
  readonly attribute unsigned long availHeight;

  [Documentation=
   "<p>The {@name} {@type} must return the width of the output device.</p>"
  ]
  readonly attribute unsigned long width;

  [Documentation=
   "<p>The {@name} {@type} must return the height of the output device.</p>"
  ]
  readonly attribute unsigned long height;

  [Documentation=
   "<p>The {@name} {@type} must return the number of bits allocated to\
    colors (i.e. excluding the alpha channel) in the output device. If the\
    output device does not support colors these attributes\
    must return zero.</p>"
  ]
  readonly attribute unsigned long colorDepth;

  [Documentation=
   "<p>The {@name} {@type} must return the value returned by the <code>colorDepth</code> attributed.</p>"
  ]
  readonly attribute unsigned long pixelDepth;

};
